version: 2
updates:
  # Enable version updates for Cargo dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "4n6h4x0r"
    commit-message:
      prefix: "deps:"
      include: "scope"
    
  # GitHub Actions updates (reduced frequency - SHA pinning handled by Pinact)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"      # Reduced from weekly to monthly
      day: "monday"  
      time: "09:00"
    open-pull-requests-limit: 3  # Reduced from 5 to 3
    reviewers:
      - "4n6h4x0r"
    commit-message:
      prefix: "ci:"
      include: "scope"
    # Security: Only allow patch and minor updates for actions
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    # Group related GitHub Actions updates  
    groups:
      github-actions:
        patterns:
          - "actions/*"
          - "github/*"
        update-types:
          - "patch"
          - "minor"