name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@5d458579430fc14a04a08a1e7d3694f545e91ce6 # stable
      with:
        components: rustfmt, clippy
    
    - name: Cache cargo registry
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    
    - name: Check formatting
      run: cargo fmt --all -- --check
    
    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
    
    - name: Run tests
      run: cargo test --verbose
    
    - name: Build domfuzz for integration tests
      run: cargo build --release
    
    - name: Run integration tests
      run: |
        cd tests/domfuzz_tester
        DOMFUZZ_BIN=../../target/release/domfuzz cargo run
      env:
        DOMFUZZ_BIN: ../../target/release/domfuzz

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@5d458579430fc14a04a08a1e7d3694f545e91ce6 # stable
    
    - name: Cache cargo registry
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-integration-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-integration-
    
    - name: Build domfuzz
      run: cargo build --release
    
    - name: Run integration tests
      run: |
        cd tests/domfuzz_tester
        DOMFUZZ_BIN=../../target/release/domfuzz cargo run
      env:
        DOMFUZZ_BIN: ../../target/release/domfuzz

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@5d458579430fc14a04a08a1e7d3694f545e91ce6 # stable
    
    - name: Cache cargo registry
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-audit-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-audit-
    
    - name: Install cargo-audit and cargo-auditable
      run: |
        cargo install --locked cargo-audit
        cargo install --locked cargo-auditable
    
    - name: Build with auditable metadata
      run: cargo auditable build --release
    
    - name: Run cargo audit
      run: cargo audit
    
    - name: Run cargo audit for dependencies
      run: cargo audit --db advisory-db --json | tee audit-report.json
    
    - name: Audit built binary
      run: cargo audit bin target/release/domfuzz
    
    - name: Upload audit report
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      if: always()
      with:
        name: security-audit-report
        path: audit-report.json

  cargo-vet:
    name: Cargo Vet
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@5d458579430fc14a04a08a1e7d3694f545e91ce6 # stable
    
    - name: Cache cargo registry
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-vet-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-vet-
    
    - name: Install cargo-vet
      run: cargo install --locked cargo-vet
    
    - name: Initialize cargo-vet (if needed)
      run: |
        if [ ! -f "supply-chain/config.toml" ]; then
          cargo vet init
        fi
    
    - name: Run cargo-vet check
      run: cargo vet --locked || echo "cargo-vet found issues - review required"
    
    - name: Upload vet report
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      if: always()
      with:
        name: cargo-vet-report
        path: supply-chain/

  trivy-security:
    name: Trivy Security Scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    
    - name: Run Trivy vulnerability scanner in repo mode
      uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
    
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@f1f6e5f6af878fb37288ce1c627459e94dbf7d01 # v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'rust' ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    
    - name: Initialize CodeQL
      uses: github/codeql-action/init@f1f6e5f6af878fb37288ce1c627459e94dbf7d01 # v3
      with:
        languages: ${{ matrix.language }}
        queries: +security-and-quality
    
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@5d458579430fc14a04a08a1e7d3694f545e91ce6 # stable
    
    - name: Cache cargo registry
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-codeql-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-codeql-
    
    - name: Build project
      run: cargo build --release
    
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@f1f6e5f6af878fb37288ce1c627459e94dbf7d01 # v3
      with:
        category: "/language:${{matrix.language}}"

  secret-scanning:
    name: Secret Scanning
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        fetch-depth: 0
    
    - name: Run Gitleaks
      uses: gitleaks/gitleaks-action@44c470ffc35caa8b1eb3e8012ca53c2f9bea4eb5 # v2.3.6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }} # Only needed for commercial use
    
    - name: Upload Gitleaks report
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      if: always()
      with:
        name: gitleaks-report
        path: results.sarif

  license-compliance:
    name: License Compliance Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@5d458579430fc14a04a08a1e7d3694f545e91ce6 # stable
    
    - name: Cache cargo registry
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-license-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-license-
    
    - name: Install cargo-license
      run: cargo install --locked cargo-license
    
    - name: Generate license report
      run: cargo license --json > licenses.json
    
    - name: Check for forbidden licenses
      run: |
        # Check for copyleft licenses that might be problematic
        FORBIDDEN=$(jq -r '.[] | select(.license | test("GPL-2.0|GPL-3.0|AGPL|LGPL"; "i")) | .name' licenses.json)
        if [ -n "$FORBIDDEN" ]; then
          echo "::warning::Potentially problematic licenses found:"
          echo "$FORBIDDEN" | while read pkg; do
            echo "::warning::$pkg"
          done
        fi
        
        # Check for unknown/missing licenses
        UNKNOWN=$(jq -r '.[] | select(.license == null or .license == "" or .license == "UNKNOWN") | .name' licenses.json)
        if [ -n "$UNKNOWN" ]; then
          echo "::error::Dependencies with unknown licenses found:"
          echo "$UNKNOWN" | while read pkg; do
            echo "::error::$pkg has unknown license"
          done
          exit 1
        fi
    
    - name: Upload license report
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      if: always()
      with:
        name: license-report
        path: licenses.json

  sbom-generation:
    name: SBOM Generation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@5d458579430fc14a04a08a1e7d3694f545e91ce6 # stable
    
    - name: Cache cargo registry
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-sbom-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-sbom-
    
    - name: Install SBOM generators
      run: |
        cargo install --locked cargo-cyclonedx
        cargo install --locked cargo-sbom
    
    - name: Generate CycloneDX SBOM
      run: |
        cargo cyclonedx --format json --output-file sbom-cyclonedx.json
        cargo cyclonedx --format xml --output-file sbom-cyclonedx.xml
    
    - name: Generate SPDX SBOM
      run: cargo sbom --output-format spdx-json --output-file sbom-spdx.json
    
    - name: Generate human-readable SBOM
      run: |
        echo "# Software Bill of Materials (SBOM)" > SBOM.md
        echo "Generated on: $(date -u)" >> SBOM.md
        echo "Project: domfuzz" >> SBOM.md
        echo "" >> SBOM.md
        echo "## Dependencies" >> SBOM.md
        cargo tree --format "{p} - {l}" | sed 's/^/- /' >> SBOM.md
    
    - name: Upload SBOM artifacts
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: sbom-reports
        path: |
          sbom-cyclonedx.json
          sbom-cyclonedx.xml
          sbom-spdx.json
          SBOM.md
    
    - name: Attach SBOM to release
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        # Create combined SBOM archive for releases
        tar -czf domfuzz-sbom-${{ github.ref_name }}.tar.gz sbom-*.json sbom-*.xml SBOM.md
    
    - name: Upload release SBOM
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: release-sbom
        path: domfuzz-sbom-*.tar.gz

  openssf-scorecard:
    name: OpenSSF Scorecard
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write
      contents: read
      actions: read
    steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        persist-credentials: false
    
    - name: Run OpenSSF Scorecard
      uses: ossf/scorecard-action@62b2cac7ed8198b15735ed49ab1e5cf35480ba46 # v2.4.0
      with:
        results_file: scorecard-results.sarif
        results_format: sarif
        repo_token: ${{ secrets.SCORECARD_READ_TOKEN || secrets.GITHUB_TOKEN }}
        publish_results: true
    
    - name: Upload Scorecard results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@f1f6e5f6af878fb37288ce1c627459e94dbf7d01 # v3
      with:
        sarif_file: scorecard-results.sarif
    
    - name: Upload Scorecard results as artifact
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: scorecard-results
        path: scorecard-results.sarif

  verify-action-pins:
    name: Verify Action SHA Pins
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    
    - name: Setup Node.js
      uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
      with:
        node-version: '20'
    
    - name: Install pin-github-action
      run: npm install -g pin-github-action
    
    - name: Verify all actions are pinned to SHA
      run: |
        echo "Checking that all GitHub Actions are pinned to SHA hashes..."
        if pin-github-action --check .github/workflows/*.yml; then
          echo "✅ All GitHub Actions are properly pinned to SHA hashes"
        else
          echo "❌ Some actions are not pinned to SHA hashes"
          echo "Run: pin-github-action .github/workflows/*.yml to fix"
          exit 1
        fi

  commit-verification:
    name: Commit Verification
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        fetch-depth: 0
    
    - name: Install gitsign for Sigstore verification
      run: |
        # Install gitsign for Sigstore signature verification
        go install github.com/sigstore/gitsign@latest
        echo "$HOME/go/bin" >> $GITHUB_PATH
    
    - name: Verify commit signatures
      run: |
        echo "Checking Sigstore commit signatures..."
        
        # Check for Sigstore signature
        if git log --show-signature -1 2>&1 | grep -q "gitsign: Good signature"; then
          echo "✅ Latest commit is Sigstore signed and verified"
          git log --show-signature -1 --oneline
        elif git log --show-signature -1 2>&1 | grep -q "gitsign: "; then
          echo "⚠️ Latest commit has Sigstore signature but verification failed"
          echo "::warning::Sigstore signature verification failed"
          git log --show-signature -1 --oneline
        else
          echo "⚠️ Latest commit is not Sigstore signed"
          echo "::warning::Commit is not signed with Sigstore - enable gitsign"
          git log -1 --oneline
        fi
    
    - name: Check recent commits signing
      run: |
        echo "Checking last 10 commits for Sigstore signatures..."
        UNSIGNED=0
        TOTAL=0
        
        git log --format="%H %s" -10 | while read hash subject; do
          TOTAL=$((TOTAL + 1))
          
          # Check Sigstore signature
          if git log --show-signature -1 $hash 2>&1 | grep -q "gitsign: Good signature"; then
            echo "✅ Sigstore Signed: $hash - $subject"
          else
            UNSIGNED=$((UNSIGNED + 1))
            echo "⚠️ Unsigned: $hash - $subject"
          fi
        done
        
        echo "Sigstore signature summary for last 10 commits completed"
    
    - name: Generate commit verification report
      run: |
        echo "# Sigstore Commit Verification Report" > commit-verification.md
        echo "Generated: $(date -u)" >> commit-verification.md
        echo "" >> commit-verification.md
        echo "## Latest Commit" >> commit-verification.md
        git log --show-signature -1 >> commit-verification.md
        echo "" >> commit-verification.md
        echo "## Last 10 Commits Sigstore Status" >> commit-verification.md
        
        git log --format="%h %s" -10 | while read hash subject; do
          if git log --show-signature -1 $hash 2>&1 | grep -q "gitsign: Good signature"; then
            echo "- $hash ✅ Sigstore $subject" >> commit-verification.md
          else
            echo "- $hash ❌ Unsigned $subject" >> commit-verification.md
          fi
        done
    
    - name: Upload commit verification report
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: commit-verification-report
        path: commit-verification.md

  semgrep-sast:
    name: Semgrep SAST
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    
    - name: Run Semgrep
      run: |
        semgrep \
          --config=auto \
          --sarif \
          --output=semgrep-results.sarif \
          --error \
          --verbose \
          --exclude="target/" \
          --exclude="tests/" \
          .
    
    - name: Upload Semgrep results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@f1f6e5f6af878fb37288ce1c627459e94dbf7d01 # v3
      if: always()
      with:
        sarif_file: semgrep-results.sarif
    
    - name: Upload Semgrep results as artifact
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      if: always()
      with:
        name: semgrep-results
        path: semgrep-results.sarif